version: '3.4'

services:
  joballey_pg:
    container_name: joballey_pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres_joballey_pg:/var/lib/postgresql/data
    networks:
      - joballey_network
  rabbitmq:
    container_name: rabbitmq
    hostname: host-queue
    volumes:
      - ./.containers/queue/data/:/var/lib/rabbitmq
      - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - joballey_network
  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6380:6379"
    networks:
      - joballey_network
  joballey_mssql:
    container_name: joballey_mssql
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=.abcABC123#
    - MSSQL_DATABASE=joballey_mssql
    restart: always
    ports:
      - "1433:1433"
    networks:
      - joballey_network
    volumes:
      - mssql_data:/var/opt/mssql

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=https://+:8081
      - ConnectionStrings__Database=Server=joballey_mssql,1433;Database=db_identity;User Id=sa;Password=.abcABC123#;Encrypt=False;TrustServerCertificate=True
      - HostSettings__Environment=docker
    depends_on:
      - joballey_mssql
    ports:
      - 7001:8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - joballey_network

  blog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=https://+:8081
      - ConnectionStrings__Database=Server=joballey_mssql,1433;Database=db_blog;User Id=sa;Password=.abcABC123#;Encrypt=False;TrustServerCertificate=True
      - HostSettings__Environment=docker
    depends_on:
      - joballey_mssql
    ports:
      - 7002:8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - joballey_network

  storage.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=https://+:8081
    ports:
      - 7003:8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - joballey_network

  job.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=https://+:8081
      - ConnectionStrings__Database=Server=joballey_pg;Port=5432;Database=db_job;Username=postgres;Password=postgres;Include Error Detail=true
      - HostSettings__Environment=docker
    depends_on:
      - joballey_pg
    ports:
      - 7004:8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - joballey_network

  yarpapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      - identity.api
      - blog.api
      - storage.api
    ports:
      - 7070:8080
      - 7000:8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - joballey_network

networks:
  joballey_network:
    driver: bridge

volumes:
  postgres_joballey_pg:
  mssql_data:  



